### PR TITLE
Review / Cleanup

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by mllg** [comment]
I renamed some files and cleaned up. Additional points:

* Do we need `ltss()`? Is there a use case for this?
* `as.data.table.mlr_tuning_spaces()` could hold more information, e.g. the number of hyperparameters as well as their names (as list column)
* The discussed sugar for learner creation is still missing.
* We should at least add some regression learners before the release.

**Comment by mllg** [comment]
Two things I'm not sure about: should we really depend on mlr3tuning (I've removed it, but I have second thoughts) and do we need to add a field `packages` so that we can automatically load the required packages (mlr3cluster, mlr3proba, ...) to construct the learner.

**Comment by mllg** [comment]
Added a field `package`.

**Comment by jakob-r** [comment]
Do we want to do anything smart about the regression learners or just copy paste? 
I think the idea of @be-marc was, to have this `set` object and use it to create regr and classif learners. But now it looks more cumbersome (also with the roxygen stuff)

**Comment by be-marc** [comment]
I wanted your opinion on the regression learner. Yes it looks more cumbersome now with the roxygen stuff. Maybe just copy paste.

**Comment by jakob-r** [comment]
One concern: Currently we can create garbage TuningSpaces bc. we don't check, whether the values are actually feasible.

**Comment by be-marc** [comment]
> One concern: Currently we can create garbage TuningSpaces bc. we don't check, whether the values are actually feasible.

`test_tuning_spaces.R` should find infeasible configurations

**Comment by be-marc** [comment]
> The discussed sugar for learner creation is still missing.

`TuningSpace$get_learner(...)` is included now. I added `...` which is passed to `lrn()`. So you can set e.g. the predict type in one go.

**Comment by be-marc** [comment]
> Do we need ltss()? Is there a use case for this?

To get multiple learners with their default tuning space?

**Comment by mllg** [comment]
> To get multiple learners with their default tuning space?

Yes, but what problem are you trying to solve where you need a list of multiple tuning spaces? Not saying we have to remove it, but I'm curious if I'm missing the point here.

**Comment by jakob-r** [comment]
> > One concern: Currently we can create garbage TuningSpaces bc. we don't check, whether the values are actually feasible.
> 
> `test_tuning_spaces.R` should find infeasible configurations

True, and `add_tuning_space` is not exported, so garbage in, garbage out is ok as long as we test for no *garbage in*. But should we test that our test actually spots that? Maybe it's obvious that it works? I was just looking at the test coverage...

**Pull request merged**
